classDiagram
    class SistemaInfinitHub {
        <<interface>>
        +cadastrarProduto(produto)
        +removerProduto(nome)
        +pesquisarProdutoPorNome(nome)
        +listarTodosProdutos()
        +pesquisarProdutosPorCategoria(categoria)
        +listarProdutosComEstoqueDisponivel()
        +reporEstoque(nome, qtd, custo)
        +cadastrarPedido(pedido)
        +removerPedido(codigo)
        +listarPedidosPorStatus(status)
        +getSaldoAtual()
        +setSaldoAtual(saldo)
        +calcularFaturamentoTotal()
        +calcularLucroTotal()
        +salvarDados()
        +recuperarDados()
    }

    class InfinitHubEcommerce {
        -Map produtos
        -Map pedidos
        -double saldoAtual
    }

    class Produto {
        -String nome
        -double precoVenda
        -double precoCusto
        -int quantidadeEmEstoque
    }

    class Pedido {
        -String codigo
        -List itens
        -LocalDateTime dataHoraPedido
    }

    SistemaInfinitHub <|.. InfinitHubEcommerce
    InfinitHubEcommerce "1" *-- "*" Produto
    InfinitHubEcommerce "1" *-- "*" Pedido
    Pedido "1" *-- "1..*" ItemPedido
    ItemPedido "1" --> "1" Produto
